name: Compilar SofiaWM (Openbox Fork)
on:
  push:
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Instalar dependências do X11 e C
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
        libx11-dev libxft-dev libxext-dev libxml2-dev libxrender-dev \
        libxrandr-dev libxcursor-dev libxinerama-dev libpango1.0-dev \
        libimlib2-dev libglib2.0-dev gettext autopoint intltool \
        libcairo2-dev libpangocairo-1.0-0 docbook-to-man

    - name: Configurar e Compilar
      run: |
        export CAIRO_CFLAGS=$(pkg-config --cflags cairo cairo-xlib pangocairo)
        export CAIRO_LIBS=$(pkg-config --libs cairo cairo-xlib pangocairo)
        export CFLAGS="$CAIRO_CFLAGS"
        export LDFLAGS="$CAIRO_LIBS"
        ./bootstrap
        ./configure
        make -j$(nproc)

    - name: Organizar Pacote SofiaWM
      run: |
        mkdir dist
        cp openbox/.libs/openbox dist/sofiawm
        cp obrender/.libs/libobrender.so* dist/
        cp obt/.libs/libobt.so* dist/

    - name: Salvar Pacote Completo (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: sofiawm-bin
        path: dist/
